version: '3'

services:
  aprendize-db:
    container_name: aprendize-db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=aprendize-dev-db
      - POSTGRES_PASSWORD=rjL4QxDG7PD0FTdgW2hT
  redis-db:
    container_name: redis-db
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
